version: '3'

dotenv: ['.env']

tasks:
  ##############################
  ### LINT
  ##############################
  lint:
    cmds:
      - bash -c "$(curl -fsSL https://gist.githubusercontent.com/Elijas/ce4480d070d4726fe7eb1863d1afd58d/raw/657b0bfea2b660ee3b0938c79f53418a03229cf3/init_generator.sh)"
      - uv run ruff check --fix-only
    desc: Run ruff to check and fix code style issues
    aliases: [l]
  upgrade-dependencies:
    desc: Upgrade all project dependencies to their latest compatible versions
    cmds:
      - uv sync --refresh --upgrade
      - uvx --from baml-agents --with regex update-baml --target-version "$(uv pip list | grep baml-py | awk '{print $2}')" --search-root-path . --verbose false
    aliases: [ud]
  generate-commit-message:
    desc: Generate a commit message
    cmds:
      - task: upgrade-dependencies
      - task: lint
      - git add -A
      - git status
      - dotenv run uvx --refresh --from baml-agents --with regex --with pyperclip generate-commit-message --model gpt-4o
    aliases: [gcm]
